server:
  port: 8080


spring:
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:8081/starterdemo}
    username: ${DATABASE_USERNAME:starterdemo}
    password: ${DATABASE_PASSWORD:starterdemo}